- name: install nginx
  hosts: frontend
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
       name: nginx
       state: present
   - name: start the nginx service
     ansible.builtin.service:
       name: nginx
        state: started 
        enabled: yes 
   - name: remove the default config
     ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

   - name: create the html dir
     ansible.builtin.file:
      path: /usr/share/nginx/html
      state: present

   - name: d/w the config
     ansible.builtin.get_url:
       url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
       dest: /tmp/frontend.zip

   - name: untar the config
     ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes #The source archive (frontend.zip) already exists on the remote (target) machine. Do not copy it from the Ansible control node

  -  name: copy expense conf
     ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  -  name: restart nginx
     ansible.builtin.service:
      name: nginx
      state: restarted